apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: ugodowy518wachta/trigger-mesh:basic-app
        ports:
        - containerPort: 5000
