apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: trigger-mesh-demo-app.com
      http:
        paths:
          - path: /basic
            pathType: Prefix
            backend:
              service:
                name: basic-app-service
                port:
                  number: 80
          - path: /premium
            pathType: Prefix
            backend:
              service:
                name: premium-app-service
                port:
                  number: 80
          - path: /legacy
            pathType: Prefix
            backend:
              service:
                name: legacy-app-service
                port:
                  number: 80
